### ISSUE TITLE
[ISSUE] Unsupported Version of Elasticsearch [8.7.1] used in Helm Chart

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda/camunda-platform-helm#1017]
**Describe the issue:**
According to the documentation, all Camunda Components require Elasticsearch 8.8.x+. 
https://docs.camunda.io/docs/reference/supported-environments/ 

**Actual behavior:**

The Helm Chart uses Elasticsearch 8.7.1

**Expected behavior:**

Helm Chart uses a supported Elasticsearch version

**How to reproduce:**

helm install camunda camunda/camunda-platform

kubectl describe sts camunda-elasticsearch-master

**Logs:**

```
  Containers:
   elasticsearch:
    Image:       docker.io/bitnami/elasticsearch:8.7.1
    Ports:       9200/TCP, 9300/TCP
    Host Ports:  0/TCP, 0/TCP
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:      1
      memory:   2Gi
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: GCP
- Helm CLI version: version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
- Chart version: 8.3.1
- Values file:  default

**Comment by aabouzaid** [comment]
Thanks @ManuelDittmar for reporting that.

It has been fixed in the latest version of C8 Helm chart 8.3.2 (it happened because we pin the ES version in [Renovate bot config](https://github.com/camunda/camunda-platform-helm/blob/dfa23406c7cd2faba0e7a3a4a35b468a164d1f8d/.github/renovate.json5#L57), and we will find a way to connect Renovate with the apps to get the latest supported ES version)
