### ISSUE TITLE
[TASK] Remove development notes from the chart before releasing it

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#1089]
**Related to:**

Support team request.

**Overview:**

Some of our users are confused by the development notes in the chart values and manifests (e.g., `TODO` and `NOTE` sections).

**Actions:**

- Remove development notes from the chart before releasing it (that could be done in the release pipeline just before the release).

**Comment by drodriguez-305** [comment]
Hey @aabouzaid ,

I identified all the files that have TODO and NOTES below. For the ones in the test directory I am guessing we can ignore these since its our unit test. 

**Files to ignore**
./test/unit/web-modeler/golden/deployment-webapp.golden.yaml
./test/unit/connectors/goldenfiles_test.go
./test/unit/identity/golden/deployment.golden.yaml
./test/unit/keycloak_statefulset_test.go
./test/unit/operate/configmap_test.go
./test/unit/tasklist/configmap_test.go
./test/unit/ingress_test.go
./test/integration/testsuites/core/testsuites/core.yaml
./test/integration/testsuites/base/job.yaml
./test/integration/testsuites/preflight/testsuites/preflight.yaml
./test/integration/scenarios/vars/dynamic.env
./test/integration/scenarios/chart-with-web-modeler/values-web-modeler-enabled.yaml
./test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
./test/integration/scenarios/lib/testsuite-deploy-taskfile.yaml
./test/integration/scenarios/fixtures/values-integration-test.yaml

Files to remove TODO and NOTES + additional lines 
./Chart.yaml
./charts/identity/templates/deployment.yaml
./charts/identity/templates/configmap-env-vars.yaml
./templates/web-modeler/deployment-webapp.yaml
./templates/connectors/_helpers.tpl
./templates/release-configmap.yaml
./templates/operate/deployment.yaml
./templates/tasklist/deployment.yaml
./templates/console/_helpers.tpl
./values.yaml

my thoughts were using sed to edit and remove the lines and maybe have an output on the changes of the files. Are there any notes/todos we want to keep is the real question or keep a log of them?
