### ISSUE TITLE
[ISSUE] latest tag of operate image points to 8.4.6 instead of 8.5.0

### ISSUE THREAD

**Issue by Benjoyo** [camunda/camunda-platform-helm#1641]
**Describe the issue:**

Not a helm charts issue, but in the absence of a more suitable place:

the latest tag of the operate image points to 8.4.6 (probably overwritten due to a race condition?) instead of 8.5.0.
Not sure if there is a general incompatibility or I was just unlucky, but for me that lead to a completely broken Operate when pulling the whole set of platform images with tag latest.

**Actual behavior:**

latest points to 8.4.6

**Expected behavior:**

latest points to 8.5.0

**How to reproduce:**

look at docker hub

**Logs:**
-

**Environment:**
-

Thanks :)

**Comment by aabouzaid** [comment]
@Benjoyo The latest tag looks good to me on the https://hub.docker.com/r/camunda/optimize/tags

It was updated 18 days ago, so I'd guess the issue is that you are using `latest` but didn't set `global.image.pullPolicy: Always` and the old image was on the machine and used what was there which is `8.4.6`.

In general, using the latest tag is not recommended especially for production envs, but if you use then the `pullPolicy` should be `Always` to get the latest image every time.

![Screenshot 2024-04-23 at 12-11-42 camunda_optimize Tags Docker Hub](https://github.com/camunda/camunda-platform-helm/assets/6760103/df0d3268-dc41-4859-a033-45f144fea59c)

**Comment by aabouzaid** [comment]
@Benjoyo Not sure if that was an issue in the [Docker Repo](https://hub.docker.com/r/camunda/operate/tags) but looks like it's fixed now by the Operate team.

Also, in general, using the latest tag is not recommended especially for production envs, but if you use then ensure that `pullPolicy` is set to `Always` to get the latest image every time (I know it's not related to your issue, but good to remember).

![Screenshot 2024-04-23 at 12-18-14 camunda_operate Tags Docker Hub](https://github.com/camunda/camunda-platform-helm/assets/6760103/01a009d3-b8f4-412f-987f-b6e3f384a075)
