### ISSUE TITLE
[ISSUE] Context paths are getting duplicated in alpha

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#2332]
**Describe the issue:**

When using a combined ingress, and navigating to a component that has moved to the monorepo, such as operate or tasklist, you will get a duplicate contextPath:

![2024-09-11-114143_grim](https://github.com/user-attachments/assets/a503a3bd-e5dd-416a-8871-9fac76a5dc3f)
`https://demo.ci.distro.ultrawombat.com/tasklist/tasklist`

![2024-09-11-113957_grim](https://github.com/user-attachments/assets/7783a300-5d55-4dab-9a1b-fcc375ce9c87)
`https://demo.ci.distro.ultrawombat.com/operate/operate`

I suspect the reason for this issue is that we are handling the `/operate` endpoint inside the ingress in addition to inside the unified docker image for tasklist and operate.

I also suspect this issue will affect separated ingress by forcing a `/operate` to the end of the url such as:
```
https://operate.demo.ci.distro.ultrawombat.com/operate
```

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by jessesimpson36** [comment]
https://github.com/camunda/distribution/issues/306

**Comment by aabouzaid** [comment]
I'm checking this issue with the QA team now.

**Comment by aabouzaid** [comment]
The dev team stated that it is an expected behavior as now we are moving to the mono jar.

From Helm's side, it's hard to make any change to keep the Ingress link as we had in the past, `/operate` instead of `/operate/operate` without depending on the Ingress controller specifications (like Nginx).

So, for now, we keep it, given it's not making any functional issues.
This will be reviewed once we have the mono jar used by default.
