### ISSUE TITLE
[ENHANCEMENT] Add variable for camunda.operate.elasticsearch.indexPrefix

### ISSUE THREAD

**Issue by galingerv** [camunda/camunda-platform-helm#2716]
**Describe the use case:**

To use single common Elasticsearch for 2 different zeebe clusters and corresponding 2 Operate instances, I have to specify prefixes for indices: 

- camunda.operate.zeebeElasticsearch.prefix
- camunda.operate.elasticsearch.indexPrefix

Helm chart contains variable `global.elasticsearch.prefix` that specifies the `camunda.operate.zeebeElasticsearch.prefix` property, but none I've found for `camunda.operate.elasticsearch.indexPrefix`

**Describe the enhancement/feature:**

Add variable for `camunda.operate.elasticsearch.indexPrefix`

**Desired outcome and acceptance tests:**

Variable added

**Comment by aabouzaid** [comment]
@galingerv Thanks for opening this issue :raised_hands: 

AFAIK the prefix isn't supported in all apps of 8.6 and below (namely Optimize)
We will support that in 8.7 as shown in PR no. https://github.com/camunda/camunda-platform-helm/pull/2643/

So I'd close this task as no action is needed for it because consistency is not possible for all apps (if you want to do that for some apps like Operate and Tasklist, you can use `operate.configuration` and `tasklist.configuration` for Camunda 8.6 and below).
