### ISSUE TITLE
Add support for podSecurityContext

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-platform-helm#322]
Currently, the zeebe and zeebe-gateway subchart only allow the configuration for the `containerSecurityContext`, but it would be good to also support the pod level securityContext to for example configure the `fsGroup`.

See the reference for the PodSecurityContext https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podsecuritycontext-v1-core vs the container security context https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#securitycontext-v1-core which doesn't allow to set the fsGroup.

Came up via https://jira.camunda.com/browse/SUPPORT-13730

**Comment by menski** [comment]
Additionally add documentation/ comments for the other 2 required changes so that users can do that easily,

- Set the zeebe.configMap.defaultMode to 774 to have the startup.sh to execute in the values.yaml  - Needs documentation / comment in values.yaml so that when we start as non-root user, we would need this change applied
- Set runAsUser and runAsGroup to 1000 to set to the zeebe user : Needs documentation / comment in values.yaml to use this UID:GID number to start as non-root so that we don’t need to go looking for it in the container, any other number other than 1000 like 860 did not work

**Comment by npepinpe** [comment]
Do we still need these? Regarding OpenShift, what you want is `runAsUser: null` (which assigns some arbitrary UID), and you don't need to touch the rest as OpenShift will give you `fsGroup: 0`. The `defaultMode` only needs to be `0754` in this case (or hell, even `0554`), as you never need to write to any of these.

See https://github.com/camunda/camunda-platform-helm/issues/345

Part of the OpenShift epic will be to provide a documented template `values.yaml` file. Would that cover what you wanted?

We should still add the `podSecurityContext` for the gateway though, so I wouldn't close this issue. Just addressing menski's comment.

**Comment by menski** [comment]
@aabouzaid can you check if we fixed this, if not let's put it back to backlog

**Comment by aabouzaid** [comment]
This has been fixed by #412 [configure securityContext for pod and container](https://github.com/camunda/camunda-platform-helm/pull/412).

It will be part of next release (Chart v8.0.14).
