### ISSUE TITLE
Error in Zeebe Gateway

### ISSUE THREAD

**Issue by widdix123** [camunda/camunda-platform-helm#357]
I need to understand why are we getting this below error in the workflow. There is no error reported on the pods 
```
09:25:02.359 | zeebe | [xxxxx-prod-file-xxxxx-set-status] ERROR: Grpc Stream Error: 8 RESOURCE_EXHAUSTED: Expected to activate jobs of type 'xxx-xxx-file-emission-set-status', but no jobs available and at least one broker returned 'RESOURCE_EXHAUSTED'. Please try again later
```

**Comment by npepinpe** [comment]
This error typically indicates your brokers are overloaded. [See the docs about this](https://docs.camunda.io/docs/apis-clients/grpc/#technical-error-handling). This is normal to see during spikes. If you see this constantly, it means one or more partitions/brokers are overloaded, and you should either reduce traffic (e.g. poll for jobs less often, add exponential backoffs) or increase resources (whether scaling horizontally by adding brokers/partitions, or vertically by adding CPU/memory to existing nodes). Typically your best bet is adding partitions which will spread the work around, increasing the parallelism.

If you need more help, I would suggest the [Camunda 8 slack](https://camunda-cloud.slack.com/) or [the forums](https://forum.camunda.io/), as you will find more general help about how to use and operate Camunda 8 there (including Zeebe) than here, since here it will be primarily about the Helm charts as an means to install things.
