### ISSUE TITLE
[TASK] Sign Helm chart artifacts using Cosign

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#957]
**Related to:**

distribution/issues/18

**Overview:**

For better supply chain security, we need to sign our Helm chart artifacts.

**Actions:**

- Use the Cosign Keyless [signing](https://docs.sigstore.dev/signing/overview/) with GitHub as an OIDC provider.

```[tasklist]
### PRs
```

**Comment by drodriguez-305** [comment]
When using Cosign manually via the keyless method it goes through the oidc auth flow and uses email to create the token. This leads to using my camunda email address to verify the blob. Wrote down the steps and questions for best path forward.

**Keyless Testing Using Cosign**

There are several methods we can use to sign the blob. In this case I used the sha256 sum of the camunda platform tar file and outputted it to a text file.

`sha256sum camunda-platform-8.x.x.tgz > camunda-platform-8.x.x_checksums.txt`

Using the bundle method will output the cert and signature in one file.
`cosign sign-blob camunda-platform-8.x.x_checksums.txt --bundle cosign.bundle`

You can also output signature and cert to separate files.
`cosign sign-blob camunda-platform-8.x.x_checksums.txt --output-certificate camunda-platform-8.x.x_checksums.txt.pem --output-signature camunda-platform-8.x.x_checksums.txt.sig`

Once the command is run the auth flow initializes. In which you will be asked if you would like to continue.

> Retrieving signed certificate...
> 
> 	The sigstore service, hosted by sigstore a Series of LF Projects, LLC, is provided pursuant to the Hosted Project Tools Terms of Use, available at https://lfprojects.org/policies/hosted-project-tools-terms-of-use/.
> 	Note that if your submission includes personal data associated with this signed artifact, it will be part of an immutable record.
> 	This may include the email address associated with the account with which you authenticate your contractual Agreement.
> 	This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later, and is subject to the Immutable Record notice at https://lfprojects.org/policies/hosted-project-tools-immutable-records/.
> 
> By typing 'y', you attest that (1) you are not submitting the personal data of any other person; and (2) you understand and agree to the statement and the Agreement terms at the URLs listed above.
> Are you sure you would like to continue? [y/N] y

It then opens a browser and will let you choose to auth with GitHub, Google, or Microsoft. I used GitHub

<img width="1124" alt="oidc " src="https://github.com/camunda/camunda-platform-helm/assets/79549660/85b98cfd-cd8d-40bc-9b67-db89f3988950">

Once that is completed you receive the files needed to verify.

**Verifying the blobs**

Just going to verify the cosign.bundle to make the findings a bit easier
`cosign verify-blob camunda-platform-8.x.x_checksums.txt --bundle cosign.bundle`

The command above will not work uniess we specify --certificate-identity AND --certificate-oidc-issuer.
`Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
main.go:74: error during command execution: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode`

The main problem I see with this is it needs my email address to verify. 
`cosign verify-blob camunda-platform-8.x.x_checksums.txt --bundle cosign.bundle --certificate-identity=xxxx.xxxx@camunda.com --certificate-oidc-issuer=https://github.com/login/oauth`

Verified Output
`Verified OK`

This leads to several questions for best path forward.

1. Should we use a key-pair and store it for verification? Easiest and quickest way.
2. Find solution for GitHub actions as the auth flow works differently. It will use the GITHUB_TOKEN. When originally looking into it we ran across an issue since it uses OCI url to push and publish. (would prob need some guidance on this one)

Useful links:
https://docs.sigstore.dev/signing/quickstart/
https://edu.chainguard.dev/open-source/sigstore/cosign/how-to-sign-blobs-with-cosign/
https://github.com/marketplace/actions/cosign-installer

**Comment by aabouzaid** [comment]
@drodriguez-305 if the GH workflow has the correct permissions (namely `id-token: write`), it will not ask for any of that because it will automatically use the correct context.

Test it in the workflow because it is how we will use it (p.s. use a branch in this repo, not a fork).

**Comment by aabouzaid** [comment]
@drodriguez-305 btw, I just realized that we don't need that checksum approach since we only have 1 chart and no plans to increase that number a lot.

So you can directly sign the chart and even use the Cosign bundle instead of separating the certificate and signature.

```
cosign sign-blob camunda-platform-8.x.x.tgz --bundle camunda-platform-8.x.x.tgz.cosign.bundle
```
