### ISSUE TITLE
[Bug] Identity Base url is not configured on zeebe gateway, operate and tasklist

### ISSUE THREAD

**Issue by megglos** [camunda/camunda-platform-helm#961]
**Overview:**

The zeebe gateway requires `ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_BASEURL` to be set in order to retrieve tenants from identity. In the 8.3.0 release it isn't set yet, leading to tasklist and operate pods never getting healthy as their initial requests to zeebe fail.

Without this set the zeebe gateway can't retrieve tenants from identity and will fail on all requests sent to it.

Similar configuration is needed for Operate and Tasklist.

**Actions:**

- [x] configure `ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_BASEURL` on the zeebe gateway when multi tenancy is enabled
- [x] configure `CAMUNDA_OPERATE_IDENTITY_BASEURL` on Operate
- [x] configure `CAMUNDA_TASKLIST_IDENTITY_BASEURL` on Tasklist

**PRs:**
- [x] https://github.com/camunda/camunda-platform-helm/pull/962

**Comment by jessesimpson36** [comment]
#960 related

**Comment by aabouzaid** [comment]
I will review the PR today.

**Comment by lukas-beumer** [comment]
@aabouzaid @jessesimpson36 Even with all these environment variables set, the authentication from tasklist and operate to the zeebe-gateway doesn't work. The only relevant error I found in the debug log is:

> L:/100.65.7.199:57278 - R:camunda-platform-zeebe-gateway/100.65.125.193:26500] INBOUND HEADERS: streamId=13101 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-status: 16, grpc-message: Failed to parse bearer token, see cause for details] padding=0 endStream=true

Even if the following env var is set, it doesn't work.
```
 - name: ZEEBE_CLIENT_CONFIG_PATH
   value: /tmp/zeebe_auth_cach`
```

**Comment by aabouzaid** [comment]
Let's ask @megglos if that's related or it's another issue :thinking:

**Comment by megglos** [comment]
I see that @j-lindner is already on this topic in https://jira.camunda.com/browse/SUPPORT-18501

@j-lindner please let me know if you could use some support on this

**Comment by lukas-beumer** [comment]
@aabouzaid @megglos In fact, the lack of the environment variable was part of the problem, but not completely. The BASE_URL was missing in any case, but this did not completely help to solve the problem for us at first. I then looked at the place in the code and saw that actually all important parameters should be set. But since we provide our keycloak with our own CA over HTTPs, I still had to add the CA to the JAVA_TRUST_STORE. Then it worked.

A more meaningful logging would have been totally helpful here, instead of "Could not parse Bearer token"

The origin of this: https://github.com/camunda/zeebe/blob/967d246fef85dde69213e09e4b3d3d00aa0f4bf5/gateway/src/main/java/io/camunda/zeebe/gateway/interceptors/impl/IdentityInterceptor.java#L52

**Comment by aabouzaid** [comment]
The PR has been merged and it will be part of the next release.
