### ISSUE TITLE
[ENHANCEMENT] Possibility to set a new inbound.mode with other parameters

### ISSUE THREAD

**Issue by lukas-beumer** [camunda/camunda-platform-helm#976]
**Describe the use case:** / **Describe the enhancement/feature:**

We use the stripped down version on Camunda (KIND) in some of our testing environments. So the components "Identity", "Tasklist", "Optimize" are disabled. But now we need the component "Operate" for these tests, so that we can test the corresponding connectors. 

For our tests the variables 

```
- name: CAMUNDA_CONNECTOR_POLLING_ENABLED
  value: "true"
- name: CAMUNDA_CONNECTOR_WEBHOOK_ENABLED
  value: "true"
```

but must be set to "true" manually at the moment, otherwise the corresponding processes will not be executed. But because the authentication is disabled accordingly and therefore only the credentials "demo/demo" work, I cannot use any of the tordefined inbound.mode [disabled, credentials or oauth]. 

So there must be a way to be able to cleanly set the two variables above to true. Temporarily, it's possible to just define these variables twice so that works, but then that often causes helmet errors, like "setElementOrderList is wrong". Or there is a new "inbound.mode" which is called "none", so that simply no variable is set and I can then set it myself.

Affected line in Helm Chart:

https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/connectors/deployment.yaml#L45

In addition, a further inboundMode would then have to be allowed here: https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/connectors/_helpers.tpl#L11 - It would be enough if you could define something like "none" here, that simply no envs are set predefined.

**Comment by HamzaMasood1** [comment]
Hello,

I would like to make sure I understand before I start working on this.
I am assuming you are using our kind values yaml: https://github.com/camunda/camunda-platform-helm/blob/b6dd0fcb05e07f2209215481d50d4819ea7773ac/kind/camunda-platform-core-kind-values.yaml

As stated you have also disabled tasklist, so I also assume that you added the following to the values yaml:
```yaml
tasklist:
  enabled: false
```
When running this values yaml, you get the following pods:

```
NAME                                     READY   STATUS    RESTARTS   AGE
camunda-connectors-6c778fcbb7-mh8wr      1/1     Running   0          4m35s
camunda-elasticsearch-master-0           1/1     Running   0          4m35s
camunda-elasticsearch-master-1           1/1     Running   0          4m35s
camunda-operate-7cbccff75b-j2m9f         1/1     Running   0          4m35s
camunda-zeebe-0                          1/1     Running   0          4m35s
camunda-zeebe-gateway-5b699496c7-kkb6f   1/1     Running   0          4m35s
```

As you can see, operate is available. 
You now need to set values to `true` for the two env vars you have mentioned within the connectors component in order to test using operate. 

You are now suggesting to append another condition to this if statement, so it can accept `none` which will result in not setting these two env vars at all: https://github.com/camunda/camunda-platform-helm/blob/b6dd0fcb05e07f2209215481d50d4819ea7773ac/charts/camunda-platform/templates/connectors/_helpers.tpl#L11

**Comment by HamzaMasood1** [comment]
The problem on my side is that after helm deployment, I modified the values of the two env vars you have listed to `true`
It ended up crashing the connectors pod with `connection refused` errors. Could you please help me understand a bit more about your configuration, and why you need these env vars to be set to `true`

Also I am not sure what consequences would arrive for the connectors component if the two env vars you listed are not present when the `none` condition is satisfied in the `_helpers.tpl` file

**Comment by ttntm** [comment]
Commenting with some additional context for what I believe might be a similar use case to where the OP is coming from.

What I would like to do: 

Enable inbound connectors for a local cluster while keeping `identity` at `enabled: false`.

I tried the following:

```yaml
connectors:
  enabled: true
  # inbound:
  #   mode: "disabled"
  env:
    - name: CAMUNDA_CONNECTOR_POLLING_ENABLED
      value: "true"
    - name: CAMUNDA_CONNECTOR_WEBHOOK_ENABLED
      value: "true"
```

After `helm upgrade` I got a second `*-connectors-*` pod that kept crashing with the following error:

`s.c.c.OperateClientProdAutoConfiguration : An attempt to connect to Operate failed: ...`

I'd assume that there's 1 `*-connectors-*` pod each for in- and outbound connectors and that it was the inbound pod that kept crashing. 

A rollback (`helm rollback camunda-platform 0`) restored my prior working state and removed the 2nd `*-connectors-*` pod.

All of the above leave me with the question whether or not inbound connectors can be used this way (i.e. without keycloak etc.) at all. And if not, could we maybe get some kind of override for local installations that would make it possible based on the minimal `identity.enabled = false` config from the [docs](https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster/)?

**Comment by HamzaMasood1** [comment]
Thanks for the input @ttntm. 
The connector team got back saying that the values fo both env vars are already true by default as you can see [here](https://github.com/camunda/connectors/blob/main/connector-runtime/connector-runtime-application/src/main/resources/application.properties#L15). The values in the values.yaml can override these variables.

I am getting the same error you are getting after trying the same:
```
2023-11-17T09:51:12.571Z  WARN 1 --- [           main] s.c.c.OperateClientProdAutoConfiguration : An attempt to connect to Operate failed: io.camunda.operate.exception.OperateException: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:8081/ [localhost/127.0.0.1] failed: Connection refused
```
The variable responsible for connecting to operate is [here](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/connectors/deployment.yaml#L78). It is referencing localhost. I'm trying to see if that is the correct address that it should be referencing.

**Comment by HamzaMasood1** [comment]
I ran the platform with the default values. I added the above env vars with the inbound mode set to `oauth` and it worked successfully. This isn't really a surprise since identity is enabled and the two env vars are set to to true by default.

I wonder what will happen if I disabled identity and set inbound mode to `credentials`? If the pod runs successfully, I can then add the two above env vars and check if it still successfully runs.

**Comment by HamzaMasood1** [comment]
Seems like the connector pod does not successfully run when the inbound mode is either `credentials` or `oauth`
@lukas-beumer could you please send the full values.yaml you use for this use-case?

**Comment by igpetrov** [comment]
Hi @lukas-beumer,

Out of curiosity, why cannot you use:

```
connectors:
  enabled: true
  inbound:
    mode: credentials
```

?

The original intention was to support environments that can access operate with basic authentication, like `demo/demo`. To set up credentials, you can use environment variables `CAMUNDA_OPERATE_CLIENT_USERNAME=demo` and `CAMUNDA_OPERATE_CLIENT_PASSWORD=demo`.

Also, on a side note, when the `connectors.inbound.mode=disabled` Connectors still should be running but without inbound capabilities, like webhook or polling, however, outbound connectors, such as REST should work fine.

**Comment by lukas-beumer** [comment]
@igpetrov Thank you for your answer! The problem with inbound.mode = "credentials", my environment variables would no longer be duplicated, but then CAMUNDA_OPERATE_CLIENT_USERNAME, because this is already set with "credentials". In other words, I always have problems here.

The reason why we want to set the two parameters to "true" is that we use the Kafka Connectors as an entry point in our process models, which always has to actively search for new messages in the Kafka topic. And this is not possible if CAMUNDA_CONNECTOR_POLLING_ENABLED is set to false.

**Comment by ttntm** [comment]
Coming back to this, I got inbound connectors working using the recommended changes to the helm chart:

```yaml
connectors:
  enabled: true
  inbound:
    mode: "credentials"
    auth:
      existingSecret: "demo"
  env:
    - name: CAMUNDA_OPERATE_CLIENT_USERNAME
      value: "demo"
    - name: CAMUNDA_OPERATE_CLIENT_PASSWORD
      value: "demo"
```

Setting `existingSecret` to a value other than `""`was done because helm complained about it. I had to use the `--force` flag when running `helm upgrade` eventually though, but I did not notice any undesired results of doing that so far.

NB: I only tested the inbound webhook connector so far and that one's working (i.e. `url -X POST -H "Content-Type: application/json" -d '{"myId": 123456, "myMessage": "Hello, world!"}' http://localhost:8088/inbound/test-webhook`)

**Comment by lukas-beumer** [comment]
That's the exact problem. We don't want to use --force always. Thats because helm doesn't allow double defined environment variables.

**Comment by jessesimpson36** [comment]
I think this is no longer an issue because of #1297 .  The PR makes it so that configmaps are used primarily, rather than environment variables, so we shouldn't run into any situations where the env var is duplicated. 

I also think this means we can close the draft PR https://github.com/camunda/camunda-platform-helm/pull/1158

@hamza-m-masood , could you verify?

**Comment by jessesimpson36** [comment]
I should also clarify, that #1297 is not yet in a release. just fixed on latest main

**Comment by jessesimpson36** [comment]
@lukas-beumer , 

If I understand this correctly, 
you set your `connectors.inbound.mode` to `disabled` to avoid the environment variable duplication with the `CAMUNDA_CONNECTOR_POLLING_ENABLED` and `CAMUNDA_CONNECTOR_WEBHOOK_ENABLED` flags.  When you set `connectors.inbound.mode` to `credentials`,  you have environment variable duplication problems  due to the `CAMUNDA_OPERATE_CLIENT_USERNAME` option, because you have configured it to use a different username other than `connectors`.

I believe after the referenced PR #1297  is made into a release,  the best course of action would be to go back to setting `connectors.inbound.mode` back to `credentials` and then to set `CAMUNDA_OPERATE_CLIENT_USERNAME` to the username you want to override that setting with.

Also, I recognize now that this issue is a little old, so if this isn't a problem for you anymore, no worries. :sweat_smile:

**Comment by jessesimpson36** [comment]
@igpetrov @theburi   Do you have thoughts on whether we should support the unauthenticated inbound connector flow directly in the helm chart ?  The current workflows are to route authentication through identity,  authenticating via static credentials for situations where identity is disabled,  and disabling inbound connectors entirely.  The proposal here is for being able to make requests that aren't protected by authentication.

**Comment by theburi** [comment]
it seems to be a valid configuration.
The question is how to support it in Helm. connectors.inbound.mode is Helm-defined value. (Correct me if we have this spec in Connectors.)
I think it's fair to define it as connectors.inbound.mode: ignore

**Comment by lukas-beumer** [comment]
Using the credentials inbound mode and overriding the OPERATE_PASSWORD with demo works for us. No duplicated envs needed anymore. Thanks!

**Comment by mayur2281** [comment]
Hi @lukas-beumer 

I have identity disabled and my values.yaml is below:

```yaml
connectors:
  enabled: true
  inbound:
    mode: "credentials"
    auth:
      existingSecret: "demo"
  env:
    - name: CAMUNDA_OPERATE_CLIENT_USERNAME
      value: "demo"
```

Getting a 403 error. Error Message: Response not successful: 403


Could you pls confirm if inbound is working on connectors?
